version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  pgadmin:
    environment:
        PGADMIN_DEFAULT_EMAIL: "b20-ferraz@hotmail.com"
        PGADMIN_DEFAULT_PASSWORD: "123456"
    restart: always
    ports:
      - "9050:80"